### ISSUE TITLE
Login?

### ISSUE THREAD

**Issue by locussss** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#10]
Hi!

What is the login for  your OpenWrt?
When I use root with empty password it does not login.

Regards!

**Comment by anaelorlinski** [comment]
just ssh root@192.168.1.1 and it will not require a password
don't forget to set it later with passwd command

**Comment by locussss** [comment]
That is really  strange because with  empty password I get something like permission denied
