### ISSUE TITLE
NanoPi r4s 1gb needs testing

### ISSUE THREAD

**Issue by anaelorlinski** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#11]

**Comment by DanGunvald** [comment]
OpenWrt 21.02 2021.12.14 img does not boot from 1 gb version.

**Comment by kelvin-acosta** [comment]
The latest image https://github.com/anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds/releases/tag/r2s-21.02-2021.12.23 does now boot with 1GB version

**Comment by anaelorlinski** [comment]
Fantastic that was the purpose of adding patches on u-boot

**Comment by anaelorlinski** [comment]
Reported that booting is fine on r4s 1Gb and I tested on my own r4s 4Gb
