### ISSUE TITLE
Local Build

### ISSUE THREAD

**Issue by gary-hammer** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#13]
I'd like to know if this can be built locally, meaning on my linux system.
Why? I'd like to remove docker from the config as I do not use or plan to use docker and do not need the additional docker related network items. Also, UDP forwarding problem in kernel with docker seemed to be an issue, but that was back in July, perhaps corrected.

In any event, how can this project be built locally, if at all?

Thanks

**Comment by aw1cks** [comment]
Reading the CI configuration should give some insight: https://github.com/anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds/blob/main/.github/workflows/NanoPi-r2s-21.02.yml

**Comment by gary-hammer** [comment]
Thanks, it does.
