### ISSUE TITLE
Official upgrade method

### ISSUE THREAD

**Issue by mrpetermatyas** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#15]
Hi Anaelorlinski,

Thank you for your project and merry Christmas! :)
A quick question. I have been using the  "AO Build@2021.10.11 / LuCI openwrt-21.02 branch git-21.279.78618-2e0ff79" version for a while.
What is the official method to upgrade to the latest version with keeping the existing configuration?

Thank you,

Peter

**Comment by anaelorlinski** [comment]
I don't know if there is an official way to update the snapshot like builds. Maybe check sysupgrade on openwrt documentation ?
If you use squashfs, then the safest way is to flash the new build on a new sd card, and copy over the contents of overlay partition from the old card to the new one.
I personally use a totally different approach based on GitOps model and maintain a set of external scripts that are run over ssh on a fresh OpenWrt install. After each new build I flash the fresh release to a new sd card and apply my configuration pipeline after boot. Of course I can revert the sd card to the previous one if something is wrong, that's the huge plus of this device.
