### ISSUE TITLE
no IPSEC tab in LUCI

### ISSUE THREAD

**Issue by JuriyCherednichock** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#18]
Hello!
flashed image for NanoPI R4S.
It works great and fast
but i have some issue
i need ipsec site-to-site tunnel
installed strongswan-full
but at LUCI i see only VPN - OpenVPN tab.

**Comment by anaelorlinski** [comment]
In general for any package you need to install the corresponding LuCI package to get the package configurable in LuCI. However after a quick check I did not see any available LuCI packge for strongswan. I think your best option for now is to configure it using command line following openwrt documentation. Don't hesitate to ask for help on the openwrt forum.
