### ISSUE TITLE
Broken r8168 and gpio-button-hotplug

### ISSUE THREAD

**Issue by vngvng** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#20]
**Broken r8168 and gpio-button-hotplug packages.**

**For r8168, all openwrt source was missing**
https://sources.cdn.openwrt.org/r8168-8.049.02.tar.xz
https://sources.openwrt.org/r8168-8.049.02.tar.xz
https://mirror2.openwrt.org/sources/r8168-8.049.02.tar.xz
curl: (22) The requested URL returned error: 404

**For gpio-button-hotplug, error msg as below.**

make[2]: *** No rule to make target '/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.4.182/.config', needed by '/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/gpio-button-hotplug/.built'.  Stop.
make[2]: Leaving directory '/openwrt/package/kernel/gpio-button-hotplug'
time: package/kernel/gpio-button-hotplug/compile#0.17#0.05#0.20
    ERROR: package/kernel/gpio-button-hotplug failed to build.
make[1]: *** [package/Makefile:116: package/kernel/gpio-button-hotplug/compile] Error 1
make[1]: Leaving directory '/openwrt'
make: *** [/openwrt/include/toplevel.mk:230: package/kernel/gpio-button-hotplug/compile] Error 2

**Comment by anaelorlinski** [comment]
I started a new build and it ran successfully. Can't reproduce the problem ...
