### ISSUE TITLE
SQM upload and download mixed

### ISSUE THREAD

**Issue by twiikker** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#21]
Latest full version for Nanopi R4S.
So i just installed it yesterday and noticed that upload and download speed settings are mixed.
If i put them correctly for my 1000/500 connection (900000 for dl and 490000 for up) i get 470/470 and if i set them other way around i get 870/470.

**Comment by anaelorlinski** [comment]
Thanks for reporting, however I am not sure this issue is related to my build or a more general OpenWrt issue. I would recommend to check on OpenWrt forums or open an issue on OpenWrt github repository. Let me know if there is a fix/workaround and I could integrate it to the build.

**Comment by shark873** [comment]
> Latest full version for Nanopi R4S. So i just installed it yesterday and noticed that upload and download speed settings are mixed. If i put them correctly for my 1000/500 connection (900000 for dl and 490000 for up) i get 470/470 and if i set them other way around i get 870/470.

This is happening cause by default the interface that comes selected in SQM page is eth1 and not eth0.
