### ISSUE TITLE
Build failing, can you check if yours fails too?

### ISSUE THREAD

**Issue by shark873** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#22]
I cloned your repo, i was using it to run some builds... but the past few days they are failing when building a determinate package can you check if yours will fail too?

Amazing work here btw, thx.

**Comment by anaelorlinski** [comment]
Started a new build. Let's see what happens.

**Comment by anaelorlinski** [comment]
My builds did complete. Probably your .config seed is buggy or you are building extra packages that are broken.

**Comment by shark873** [comment]
Before the issue was related to -> https://github.com/openwrt/packages/issues/18177 <- which got fixed...

Now i have a new issue:

https://i.imgur.com/zHd1PUd.png

I have just re-done my .seed file but its still happening. Do you have any ideas? Thx.
