### ISSUE TITLE
Resetting settings on reboot

### ISSUE THREAD

**Issue by littl3viking** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#28]
In the last version (OpenWrt 21.02 2022.05.01) every time I reboot (via LUCI) the settings are reset to default.
This does not occur in OpenWrt 21.02 2022.04.28 version.
I don't have log, sorry.
Device: NanoPi R4S 4GB

**Comment by anaelorlinski** [comment]
I have no clue of what could be the change, I will generate a new build to check if problem persists

**Comment by anaelorlinski** [comment]
No feedback
