### ISSUE TITLE
stangri_repo is misconfigured

### ISSUE THREAD

**Issue by TheLinuxGuy** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#3]
On the latest images, out of the box the `opkg update` is broken due to bad configuration on the image.

https://docs.openwrt.melmac.net << is the repo that seems to be the goal to include. In their docs they recommend to store the additional repo config inside `/etc/opkg/customfeeds.conf`

I would recommend a fix, I had to do this manually today.
1. Remove broken repo stangri from /etc/opkg/customfeeds.conf
2. Configure repo properly via  `/etc/opkg/customfeeds.conf`
3. Ensure the signature key exists `echo -e -n 'untrusted comment: OpenWrt usign key of Stan Grishin\nRWR//HUXxMwMVnx7fESOKO7x8XoW4/dRidJPjt
91hAAU2L59mYvHy0Fa\n' > /etc/opkg/keys/7ffc7517c4cc0c56`

This should make your image OPKG manager work again and setup the repository properly.

**Comment by anaelorlinski** [comment]
I changed the way I include latest version of vpn-policy-routing, issue is fixed in latest release.
