### ISSUE TITLE
Can't install pppoe

### ISSUE THREAD

**Issue by mikegleasonjr** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#30]
See screenshot...

<img width="1164" alt="Screen Shot 2022-06-17 at 11 45 27 PM" src="https://user-images.githubusercontent.com/1644534/174409851-42760b3e-6f62-45e3-a52a-620110eb3c36.png">

Using latest build on a Nanopi R4S 1gb version.

Thank btw for this build, since the OpenWRT snapshot doesn't support the 1gb version.

**Comment by shark873** [comment]
> See screenshot...
> 
> <img alt="Screen Shot 2022-06-17 at 11 45 27 PM" width="1164" src="https://user-images.githubusercontent.com/1644534/174409851-42760b3e-6f62-45e3-a52a-620110eb3c36.png">
> 
> Using latest build on a Nanopi R4S 1gb version.
> 
> Thank btw for this build, since the OpenWRT snapshot doesn't support the 1gb version.

https://github.com/anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds/issues/17#issuecomment-1038908409

**Comment by mikegleasonjr** [comment]
Yeah in the meantime I learned how to compile your repo, I thank you very much, I have a working pppoe connection new 🙏👌👍
