### ISSUE TITLE
NanoPi R2S - CPU Speed Setting

### ISSUE THREAD

**Issue by Cossey** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#37]
I am wanting to know if this build includes the ability to set the clock speed of the CPU on the R2S. I only get around 500 megabit on this one, but I tried another nanopi openwrt build where I could set CPU speed to its max (overclock) and I was able to get around 910 megabit (I have proper cooling).

Thanks!

**Comment by anaelorlinski** [comment]
The overclocking patches are not included in my builds

**Comment by Cossey** [comment]
Are you able to add these over-clocking patches? This would make it perfect for my use case.
