### ISSUE TITLE
dnsmasq is built with HAVE_BROKEN_RTC, leading to Lease Time remaining always showing 'expired'

### ISSUE THREAD

**Issue by semicuda** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#4]
Currently Luci in 21.02 is expecting dhcp.leases to have an actual timestamp in the first column, otherwise all leases will show up as expired. Your config is building dnsmasq with HAVE_BROKEN_RTC, which puts the lease duration in seconds in the first column, never updating it to reflect the remaining time. To fix this, you'll need to remove this in your seed files:

`CONFIG_PACKAGE_dnsmasq_full_broken_rtc=n`

Otherwise, thanks for your great work... running perfectly fine on an r4s as main router!

**Comment by anaelorlinski** [comment]
Fixed in latest build. Thanks for reporting!
