### ISSUE TITLE
Support for branch 23.05

### ISSUE THREAD

**Issue by gokulkgm** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#44]
Hello,

As OpenWrt branch 23.05 is created and is being prepared for stable release, could you please add support for it?

Thanks

**Comment by anaelorlinski** [comment]
I will work on it, I need to upgrade my devices too :)

**Comment by gokulkgm** [comment]
Thanks, I was checking if I could try updating but not sure what patches I need.
