### ISSUE TITLE
PPPOE ?

### ISSUE THREAD

**Issue by mandgeo** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#5]
There is no pppoe as connection protocol. Full version.
Is this on purpose or a mistake? 

And, by the way, what are the differences between full and lite version?

Thanks!

**Comment by anaelorlinski** [comment]
New build with ppp (in full version) in progress

Lite version has fewer packages (no Luci, no docker, ...), this is the version I use for my router box.

**Comment by anaelorlinski** [comment]
https://github.com/anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds/releases/tag/r2s-21.02-2021.10.05
