### ISSUE TITLE
Please Update To Latest Build

### ISSUE THREAD

**Issue by adibindrianto** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#51]
Need update to openwrt 23.05.3 latest update, your repo is amazing for me

**Comment by adibindrianto** [comment]
![Screenshot_20240327-130347_Chrome](https://github.com/anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds/assets/133480318/fc5f8283-13f5-492d-bce8-b9399790bfc2)
i just changed the rules of some packages in ao-R4S-full.seed.orig and ao-R4S-full.seed but i want to build for R2S because in the repo there are no rules for changing R2S packages so i changed in R4S, but it always fails like picture, can you help me?

**Comment by anaelorlinski** [comment]
The kernel config needs some refresh too because the build does not have info about NET_SCH_CBQ
You need to add the line
```
# CONFIG_NET_SCH_CBQ is not set
```
in openwrt-23.05/steps/03_patch_openwrt.sh at line 55

**Comment by anaelorlinski** [comment]
build has completed, I will try it on my router tonight

**Comment by adibindrianto** [comment]
I also tried it and succeeded, thank you

**Comment by anaelorlinski** [comment]
please read openwrt documentation first or ask in the openwrt forum.
you would find easily that you just need to add this line to /etc/opkg/customfeeds.conf

**Comment by adibindrianto** [comment]
![IMG-20240328-WA0003](https://github.com/anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds/assets/133480318/5683e770-94fa-4446-ab67-d0625e326af2)

understand, I mean is there an additional script line for the custom feed before the build is run, maybe there is a script that needs to be added to the bottom line for the custom feed, I understand that this is vanilla openwrt if you want to add a custom feed line can you add the bottom line? and how should the script be executed?

**Comment by anaelorlinski** [comment]
The url you show contains .ipk files, already compiled packages.
So flash the cart and afterwards add "src/gz openwrt_kiddin9 https://dl.openwrt.ai/latest/packages/aarch64_generic/kiddin9" to /etc/opkg/customfeeds.conf
then run opkg update
and opkg install your extra packages.
If you want to add source packages to the build and build them, the way to do it is totally different, check how I integrate the stangri repository from source into my build.

**Comment by adibindrianto** [comment]
I'm sorry, I have followed as far as I can but when the script makes me confused then that's where I have to stop because there is a lot I don't know about the build script but thank you for responding to all my complaints

**Comment by adibindrianto** [comment]
I want to report an issue, after the first time I finished burning, Docker didn't work and couldn't display the web UI, for example Jellyfin

**Comment by adibindrianto** [comment]
Do you have a desire to make immortalwrt the same as openwrt r2s? with the latest version of vanilla immortalwrt?
