### ISSUE TITLE
R4S: CPU Management

### ISSUE THREAD

**Issue by Ankh-** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#53]
Hi!

At the OpenWRT Wiki, they talk about CPU management for the R4S. By setting specific CPU affinity you can get better performance. Is this something you can incorporate into the build?

https://openwrt.org/toh/friendlyarm/nanopi_r4s_v1#cpu_management

Kind Regards,
Paul

**Comment by anaelorlinski** [comment]
All the commands from this page will work out of the box in my builds because they are native to the linux kernel, there is no need to do extra work :)
