### ISSUE TITLE
Tracing back installed openwrt 

### ISSUE THREAD

**Issue by fg-personal** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#54]
To whom it may regard,

is "AO Build@2024.03.27" the tag for this custom build?
I am not 100% sure I got my build from here, but here's the output from the terminal on my router.
`root@OpenWrt:~# ubus call system board
{
        "kernel": "5.15.150",
        "hostname": "OpenWrt",
        "system": "ARMv8 Processor rev 4",
        "model": "FriendlyElec NanoPi R4S",
        "board_name": "friendlyarm,nanopi-r4s",
        "rootfs_type": "ext4",
        "release": {
                "distribution": "OpenWrt",
                "version": "23.05.3",
                "revision": "r23809-234f1a2efa",
                "target": "rockchip/armv8",
                "description": "AO Build@2024.03.27"
        }
}`

**Comment by anaelorlinski** [comment]
Yes 2024.03.27 is the date of build and combined with version (23.05.3) you can identify the build. AO = anaelorlinski ;)
You can identify rootfs_type to ext4. I am not sure how you can idenfity the mini vs full however, maybe check if docker is available in the image, only avail in the full version.
