### ISSUE TITLE
No thermal zone for monitoring?

### ISSUE THREAD

**Issue by mercyground** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#6]
Tried enabling thermal monitoring with collectd and also manually pulling via a script but interfaces don't exist?

https://github.com/friendlyarm/cpu-temperature-test-script

```
./capture_cpufreq_and_temp.sh: line 14: can't open /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq: no such file
./capture_cpufreq_and_temp.sh: line 18: can't open /sys/class/thermal/thermal_zone0/temp: no such file
```

#include script
```
#!/bin/bash

rm -f /tmp/cpufreq.txt
rm -f /tmp/cpu_temperature.txt

for j in $(seq $(grep -c processor /proc/cpuinfo))
do
    dd if=/dev/zero of=/dev/null bs=1 &
done 

ps | grep dd > /tmp/cpufan_testing_started
for i in {1..1800}
do
    awk '{printf ("%0.0f\n",$1/1000); }' </sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq >> /tmp/cpufan_testing_cpu-freq.txt
    if [ -f /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_cur_freq ]; then
        awk '{printf ("%0.0f\n",$1/1000); }' </sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_cur_freq >> /tmp/cpufan_testing_cpu4-freq.txt
    fi
    awk '{printf ("%0.1f\n",$1/1000); }' </sys/class/thermal/thermal_zone0/temp >> /tmp/cpufan_testing_cpu-temperature.txt
    sleep 1
done
ps | grep dd > /tmp/cpufan_testing_done

for dd in $(jobs -p) ; do kill ${dd} ; done
```

**Comment by mercyground** [comment]
OpenWrt-AO-21.02-20211005.1342-NanoPi-r4s-ext4-full.img

latest build for r4s.

**Comment by anaelorlinski** [comment]
I upgraded to latest version on my side and it works ...

`BusyBox v1.33.1 (2021-10-02 15:41:59 UTC) built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 21.02-SNAPSHOT, r16299-76d90a5eaf
 -----------------------------------------------------

AO Build@2021.10.05

root@Router2102:~# cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq
600000
root@Router2102:~# cat /sys/class/thermal/thermal_zone0/temp
47500
root@Router2102:~#`
