### ISSUE TITLE
thermal sensors

### ISSUE THREAD

**Issue by bderancourt** [anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds#8]
Hello,

I installed OpenWrt-AO-21.02-20211011.2318-NanoPi-r4s-ext4-full firmware on my R4S and tried to activate the thermal sensors, as they don't seems to work out of the box after installing the firmware.

I installed lm-sensors-detect but the detection didn't find any sensor. 
Do you have an idea how to activate the thermal sensors ? It's seems to work with FriendlyWRT.

Thank you.

**Comment by anaelorlinski** [comment]
```
root@OpenWrt:~# cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq
600000
root@OpenWrt:~# cat /sys/class/thermal/thermal_zone0/temp
47500
```
